# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- variables:
    imageName: 'nehamaurya/nodejs-helloworldapp'
    vmImageName: 'ubuntu-latest'
    dockerRegistryServiceConnection: 'dockerhub-connection'
    dockerfilePath: './Dockerfile'

- stage: Build
   displayName: Build stage
   jobs:
   - job: Build
     displayName: Build Job 
     pool:
       vmImage: $(vmImageName) 
     steps:
     - task: Docker@2
       displayName: Build and push an image to container registry
       inputs:
         containerRegistry: $(dockerRegistryServiceConnection)
         repository: '$(imageName)':'$(Build.BuildId)'
         command: 'buildAndPush'
         Dockerfile: $(dockerRegistryServiceConnection) 

