# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: ubuntu-latest

variables:
  imageName : nehamaurya/nodejs-helloworldapp

steps:
- task: Docker@2
  displayName: Login to Dockerhub
  inputs:
    command: login
    containerRegistry: dockerhub-connection
    
- task: Docker@2
  displayName: running docker build
  input: 
    repository: $(imageName):$(Build.BuildId)
    command: buildAndPush
    Dockerfile: **/Dockerfile


