apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  selector:
      matchLabels:
        app: demo-app
  replicas: 1
  template:
      metadata:
        labels:
            app: demo-app
      spec:
        containers:
        - name: demo-app
          image: nehamaurya/nodejs-helloworldapp:28
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
